/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as AuthenticatedTrocasRouteImport } from './routes/_authenticated/trocas'
import { Route as AuthenticatedRelatoriosRouteImport } from './routes/_authenticated/relatorios'
import { Route as AuthenticatedProdutosRouteImport } from './routes/_authenticated/produtos'
import { Route as AuthenticatedPrecificacaoRouteImport } from './routes/_authenticated/precificacao'
import { Route as AuthenticatedPorProdutoRouteImport } from './routes/_authenticated/por-produto'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedFinanceiroRouteImport } from './routes/_authenticated/financeiro'
import { Route as AuthenticatedDreRouteImport } from './routes/_authenticated/dre'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedComprasRouteImport } from './routes/_authenticated/compras'
import { Route as AuthenticatedAdsRouteImport } from './routes/_authenticated/ads'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicSubmitOrderRouteImport } from './routes/api/public/submit-order'

const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CheckoutRoute,
} as any)
const AuthenticatedTrocasRoute = AuthenticatedTrocasRouteImport.update({
  id: '/trocas',
  path: '/trocas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRelatoriosRoute = AuthenticatedRelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProdutosRoute = AuthenticatedProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrecificacaoRoute =
  AuthenticatedPrecificacaoRouteImport.update({
    id: '/precificacao',
    path: '/precificacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPorProdutoRoute = AuthenticatedPorProdutoRouteImport.update({
  id: '/por-produto',
  path: '/por-produto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceiroRoute = AuthenticatedFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDreRoute = AuthenticatedDreRouteImport.update({
  id: '/dre',
  path: '/dre',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedComprasRoute = AuthenticatedComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdsRoute = AuthenticatedAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSubmitOrderRoute = ApiPublicSubmitOrderRouteImport.update({
  id: '/api/public/submit-order',
  path: '/api/public/submit-order',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dre': typeof AuthenticatedDreRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/por-produto': typeof AuthenticatedPorProdutoRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/trocas': typeof AuthenticatedTrocasRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/api/public/submit-order': typeof ApiPublicSubmitOrderRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/admin': typeof AuthenticatedAdminRoute
  '/ads': typeof AuthenticatedAdsRoute
  '/compras': typeof AuthenticatedComprasRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dre': typeof AuthenticatedDreRoute
  '/financeiro': typeof AuthenticatedFinanceiroRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/por-produto': typeof AuthenticatedPorProdutoRoute
  '/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/produtos': typeof AuthenticatedProdutosRoute
  '/relatorios': typeof AuthenticatedRelatoriosRoute
  '/trocas': typeof AuthenticatedTrocasRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/submit-order': typeof ApiPublicSubmitOrderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/ads': typeof AuthenticatedAdsRoute
  '/_authenticated/compras': typeof AuthenticatedComprasRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dre': typeof AuthenticatedDreRoute
  '/_authenticated/financeiro': typeof AuthenticatedFinanceiroRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/por-produto': typeof AuthenticatedPorProdutoRoute
  '/_authenticated/precificacao': typeof AuthenticatedPrecificacaoRoute
  '/_authenticated/produtos': typeof AuthenticatedProdutosRoute
  '/_authenticated/relatorios': typeof AuthenticatedRelatoriosRoute
  '/_authenticated/trocas': typeof AuthenticatedTrocasRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/submit-order': typeof ApiPublicSubmitOrderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/checkout'
    | '/admin'
    | '/ads'
    | '/compras'
    | '/configuracoes'
    | '/dre'
    | '/financeiro'
    | '/indicadores'
    | '/metas'
    | '/pedidos'
    | '/por-produto'
    | '/precificacao'
    | '/produtos'
    | '/relatorios'
    | '/trocas'
    | '/checkout/$slug'
    | '/loja/$slug'
    | '/api/public/submit-order'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/checkout'
    | '/admin'
    | '/ads'
    | '/compras'
    | '/configuracoes'
    | '/dre'
    | '/financeiro'
    | '/indicadores'
    | '/metas'
    | '/pedidos'
    | '/por-produto'
    | '/precificacao'
    | '/produtos'
    | '/relatorios'
    | '/trocas'
    | '/checkout/$slug'
    | '/loja/$slug'
    | '/'
    | '/api/public/submit-order'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/checkout'
    | '/_authenticated/admin'
    | '/_authenticated/ads'
    | '/_authenticated/compras'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dre'
    | '/_authenticated/financeiro'
    | '/_authenticated/indicadores'
    | '/_authenticated/metas'
    | '/_authenticated/pedidos'
    | '/_authenticated/por-produto'
    | '/_authenticated/precificacao'
    | '/_authenticated/produtos'
    | '/_authenticated/relatorios'
    | '/_authenticated/trocas'
    | '/checkout/$slug'
    | '/loja/$slug'
    | '/_authenticated/'
    | '/api/public/submit-order'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  LojaSlugRoute: typeof LojaSlugRoute
  ApiPublicSubmitOrderRoute: typeof ApiPublicSubmitOrderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/_authenticated/trocas': {
      id: '/_authenticated/trocas'
      path: '/trocas'
      fullPath: '/trocas'
      preLoaderRoute: typeof AuthenticatedTrocasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/relatorios': {
      id: '/_authenticated/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof AuthenticatedRelatoriosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/produtos': {
      id: '/_authenticated/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof AuthenticatedProdutosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/precificacao': {
      id: '/_authenticated/precificacao'
      path: '/precificacao'
      fullPath: '/precificacao'
      preLoaderRoute: typeof AuthenticatedPrecificacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/por-produto': {
      id: '/_authenticated/por-produto'
      path: '/por-produto'
      fullPath: '/por-produto'
      preLoaderRoute: typeof AuthenticatedPorProdutoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/financeiro': {
      id: '/_authenticated/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof AuthenticatedFinanceiroRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dre': {
      id: '/_authenticated/dre'
      path: '/dre'
      fullPath: '/dre'
      preLoaderRoute: typeof AuthenticatedDreRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/compras': {
      id: '/_authenticated/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof AuthenticatedComprasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ads': {
      id: '/_authenticated/ads'
      path: '/ads'
      fullPath: '/ads'
      preLoaderRoute: typeof AuthenticatedAdsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/submit-order': {
      id: '/api/public/submit-order'
      path: '/api/public/submit-order'
      fullPath: '/api/public/submit-order'
      preLoaderRoute: typeof ApiPublicSubmitOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAdsRoute: typeof AuthenticatedAdsRoute
  AuthenticatedComprasRoute: typeof AuthenticatedComprasRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDreRoute: typeof AuthenticatedDreRoute
  AuthenticatedFinanceiroRoute: typeof AuthenticatedFinanceiroRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedPorProdutoRoute: typeof AuthenticatedPorProdutoRoute
  AuthenticatedPrecificacaoRoute: typeof AuthenticatedPrecificacaoRoute
  AuthenticatedProdutosRoute: typeof AuthenticatedProdutosRoute
  AuthenticatedRelatoriosRoute: typeof AuthenticatedRelatoriosRoute
  AuthenticatedTrocasRoute: typeof AuthenticatedTrocasRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAdsRoute: AuthenticatedAdsRoute,
  AuthenticatedComprasRoute: AuthenticatedComprasRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDreRoute: AuthenticatedDreRoute,
  AuthenticatedFinanceiroRoute: AuthenticatedFinanceiroRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedPorProdutoRoute: AuthenticatedPorProdutoRoute,
  AuthenticatedPrecificacaoRoute: AuthenticatedPrecificacaoRoute,
  AuthenticatedProdutosRoute: AuthenticatedProdutosRoute,
  AuthenticatedRelatoriosRoute: AuthenticatedRelatoriosRoute,
  AuthenticatedTrocasRoute: AuthenticatedTrocasRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CheckoutRouteChildren {
  CheckoutSlugRoute: typeof CheckoutSlugRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutSlugRoute: CheckoutSlugRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  LojaSlugRoute: LojaSlugRoute,
  ApiPublicSubmitOrderRoute: ApiPublicSubmitOrderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
